class: me.alf21.textdrawsystem.TextdrawSystem
name: Textdrawsystem
version: 1.0-SNAPSHOT
buildNumber: ${build.number}
buildDate: ${build.date}
authors: Alf21
description: GUI and Textdraw system that helps you to create custom GUIs and handle with Textdraws more easier